# .streamlit/config.toml

[server]
headless = true
port = 8501
enableCORS = false
enableWebsocketCompression = false
maxUploadSize = 100
enableXsrfProtection = true

[global]
theme = "light"

[theme]
primaryColor = "#4a6fa5"
backgroundColor = "#b8cfec"
secondaryBackgroundColor = "#a0b7e2"
textColor = "#333333"
font = "sans serif"
